### PR TITLE
Increase the generation of printed books

### LINKED ISSUE #15: Differentiate original books from copies in Printing Press
Currently you can use the Printing Press to create a printing plate from a book, and use that printing plate to print copies of the book. There is no distinction between originals, and copies of the book however. 

Based on an idea from Naglafer, we should create this distinction. When making a printing plate we should mark the original book as an original in some way, and then when making copies of the book with the printing plate we should likewise mark the copies as being copies of the book. This way there will be inherent value of holding original versions of books.

Going even further, we could perhaps increment the number of times a printing plate has been used to denote copies as being "First edition", "Second edition", etc. To give value to initial runs, and give successive runs less value. Or to make copies of copied books less valuable.

### PR DESCRIPTION
**Pull request by MelnCat**
Resolves #15.

This makes printing presses increase the generation of printed books. For example, original books create original printing plates, which print copy of original books. Copy of original books create copy of original printing plates, which create copy of copy books. Copy of copy books create copy of copy printing plates, which create tattered books. Tattered books cannot be used to create printing plates.

### CODE REVIEW

**Comment by Lodish** [comment]
I don't have an issue with the idea of making books that can't be copied, and making originals have more value. What will the plates themselves say though? I think all plates on civmc atm say tattered, will they work after this update?

**Comment by MelnCat** [comment]
The current plates displaying "tattered" is a bug. The printing plates will display the generation of the book used to create them, and printing plates that currently display "tattered" will create copy of original books (essentially functioning as an original printing plate).

**Comment by Lodish** [comment]
Sounds good, I assume this is just waiting for someone to review it?

**Comment by MelnCat** [comment]
Yep

**Review by Diet-Cola — APPROVED** [review]
Passing with flying colours

Will try to get the PR queue flowing asap

**Pull request merged**
